########### REST Client ### For Testing API
# baseURL
@baseURL = {{$dotenv API_URL}}
###
# check logged user data
GET {{ baseURL }}/authentication


###
# Log in 
POST {{ baseURL }}/authentication
Content-Type: application/json

{
    "email": "{{$dotenv TEST_USER_EMAIL}}",
	"password": "{{$dotenv TEST_USER_PASSWORD}}"
}

###
# Register 
POST {{ baseURL }}/authentication/register
Content-Type: application/json

{
    "email": "a@gmail.com",
	"password": "asd123asd",
    "name":"aLejandro",
    "surname":"martin linars"
}

###
# Logout
DELETE {{ baseURL }}/authentication
